# NASA Asteroids Datasets
The aim of this analysis is to explore the features associated with the hazardous asteroids

#### Importing the dataset and exploring its parameters :

In [1]:
import numpy as np 
import pandas as pd

In [2]:
original_df = pd.read_csv("nasa.csv")
original_df.head()

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),Est Dia in Feet(min),...,Asc Node Longitude,Orbital Period,Perihelion Distance,Perihelion Arg,Aphelion Dist,Perihelion Time,Mean Anomaly,Mean Motion,Equinox,Hazardous
0,3703080,3703080,21.6,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,417.388066,...,314.373913,609.599786,0.808259,57.257470,2.005764,2.458162e+06,264.837533,0.590551,J2000,True
1,3723955,3723955,21.3,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,136.717242,425.869294,0.718200,313.091975,1.497352,2.457795e+06,173.741112,0.845330,J2000,False
2,2446862,2446862,20.3,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,259.475979,643.580228,0.950791,248.415038,1.966857,2.458120e+06,292.893654,0.559371,J2000,True
3,3092506,3092506,27.4,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,57.173266,514.082140,0.983902,18.707701,1.527904,2.457902e+06,68.741007,0.700277,J2000,False
4,3514799,3514799,21.6,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,417.388066,...,84.629307,495.597821,0.967687,158.263596,1.483543,2.457814e+06,135.142133,0.726395,J2000,True

In [3]:
original_df.shape

(4687, 40)

In [4]:
original_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4687 entries, 0 to 4686
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Neo Reference ID              4687 non-null   int64
 1   Name                          4687 non-null   int64
 2   Absolute Magnitude            4687 non-null   float64
 3   Est Dia in KM(min)            4687 non-null   float64
 4   Est Dia in KM(max)            4687 non-null   float64
 5   Est Dia in M(min)             4687 non-null   float64
 6   Est Dia in M(max)             4687 non-null   float64
 7   Est Dia in Miles(min)         4687 non-null   float64
 8   Est Dia in Miles(max)         4687 non-null   float64
 9   Est Dia in Feet(min)          4687 non-null   float64
 10  Est Dia in Feet(max)          4687 non-null   float64
 11  Close Approach Date           4687 non-null   object
 12  Epoch Date Close Approach     4687 non-null   int64
 13  Relative Velocity km per sec  4687 non-null   float64
 14  Relative Velocity km per hr   4687 non-null   float64
 15  Miles per hour                4687 non-null   float64
 16  Miss Dist.(Astronomical)      4687 non-null   float64
 17  Miss Dist.(lunar)             4687 non-null   float64
 18  Miss Dist.(kilometers)        4687 non-null   float64
 19  Miss Dist.(miles)             4687 non-null   float64
 20  Orbiting Body                 4687 non-null   object
 21  Orbit ID                      4687 non-null   int64
 22  Orbit Determination Date      4687 non-null   object
 23  Orbit Uncertainity            4687 non-null   int64
 24  Minimum Orbit Intersection    4687 non-null   float64
 25  Jupiter Tisserand Invariant   4687 non-null   float64
 26  Epoch Osculation              4687 non-null   float64
 27  Eccentricity                  4687 non-null   float64
 28  Semi Major Axis               4687 non-null   float64
 29  Inclination                   4687 non-null   float64
 30  Asc Node Longitude            4687 non-null   float64
 31  Orbital Period                4687 non-null   float64
 32  Perihelion Distance           4687 non-null   float64
 33  Perihelion Arg                4687 non-null   float64
 34  Aphelion Dist                 4687 non-null   float64
 35  Perihelion Time               4687 non-null   float64
 36  Mean Anomaly                  4687 non-null   float64
 37  Mean Motion                   4687 non-null   float64
 38  Equinox                       4687 non-null   object
 39  Hazardous                     4687 non-null   bool
dtypes: bool(1), float64(30), int64(5), object(4)
memory usage: 1.4+ MB

In [5]:
original_df.isna().sum()

Neo Reference ID                0
Name                            0
Absolute Magnitude              0
Est Dia in KM(min)              0
Est Dia in KM(max)              0
Est Dia in M(min)               0
Est Dia in M(max)               0
Est Dia in Miles(min)           0
Est Dia in Miles(max)           0
Est Dia in Feet(min)            0
Est Dia in Feet(max)            0
Close Approach Date             0
Epoch Date Close Approach       0
Relative Velocity km per sec    0
Relative Velocity km per hr     0
Miles per hour                  0
Miss Dist.(Astronomical)        0
Miss Dist.(lunar)               0
Miss Dist.(kilometers)          0
Miss Dist.(miles)               0
Orbiting Body                   0
Orbit ID                        0
Orbit Determination Date        0
Orbit Uncertainity              0
Minimum Orbit Intersection      0
Jupiter Tisserand Invariant     0
Epoch Osculation                0
Eccentricity                    0
Semi Major Axis                 0
Inclination                     0
Asc Node Longitude              0
Orbital Period                  0
Perihelion Distance             0
Perihelion Arg                  0
Aphelion Dist                   0
Perihelion Time                 0
Mean Anomaly                    0
Mean Motion                     0
Equinox                         0
Hazardous                       0
dtype: int64

#### Preparing the data for analysis:

In [6]:
#droping features that we are sure that it is not important 
df = original_df.drop(columns=["Neo Reference ID","Name","Close Approach Date","Epoch Date Close Approach","Orbit Uncertainity","Orbit Determination Date"])
#droping repated features
df = df.drop(columns=["Est Dia in M(min)","Est Dia in M(max)","Est Dia in Miles(min)","Est Dia in Miles(max)",
"Est Dia in Feet(min)","Est Dia in Feet(max)","Relative Velocity km per sec","Miles per hour","Miss Dist.(Astronomical)","Miss Dist.(lunar)","Miss Dist.(miles)"])

In [7]:
df["Hazardous"] = df["Hazardous"].astype(int)
df["Hazardous"].head()

0    1
1    0
2    1
3    0
4    1
Name: Hazardous, dtype: int32

In [8]:
df.head()

,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Relative Velocity km per hr,Miss Dist.(kilometers),Orbiting Body,Orbit ID,Minimum Orbit Intersection,Jupiter Tisserand Invariant,Epoch Osculation,...,Asc Node Longitude,Orbital Period,Perihelion Distance,Perihelion Arg,Aphelion Dist,Perihelion Time,Mean Anomaly,Mean Motion,Equinox,Hazardous
0,21.6,0.127220,0.284472,22017.003799,62753692.0,Earth,17,0.025282,4.634,2458000.5,...,314.373913,609.599786,0.808259,57.257470,2.005764,2.458162e+06,264.837533,0.590551,J2000,1
1,21.3,0.146068,0.326618,65210.346095,57298148.0,Earth,21,0.186935,5.457,2458000.5,...,136.717242,425.869294,0.718200,313.091975,1.497352,2.457795e+06,173.741112,0.845330,J2000,0
2,20.3,0.231502,0.517654,27326.560182,7622911.5,Earth,22,0.043058,4.557,2458000.5,...,259.475979,643.580228,0.950791,248.415038,1.966857,2.458120e+06,292.893654,0.559371,J2000,1
3,27.4,0.008801,0.019681,40225.948191,42683616.0,Earth,7,0.005512,5.093,2458000.5,...,57.173266,514.082140,0.983902,18.707701,1.527904,2.457902e+06,68.741007,0.700277,J2000,0
4,21.6,0.127220,0.284472,35426.991794,61010824.0,Earth,25,0.034798,5.154,2458000.5,...,84.629307,495.597821,0.967687,158.263596,1.483543,2.457814e+06,135.142133,0.726395,J2000,1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4687 entries, 0 to 4686
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Absolute Magnitude           4687 non-null   float64
 1   Est Dia in KM(min)           4687 non-null   float64
 2   Est Dia in KM(max)           4687 non-null   float64
 3   Relative Velocity km per hr  4687 non-null   float64
 4   Miss Dist.(kilometers)       4687 non-null   float64
 5   Orbiting Body                4687 non-null   object
 6   Orbit ID                     4687 non-null   int64
 7   Minimum Orbit Intersection   4687 non-null   float64
 8   Jupiter Tisserand Invariant  4687 non-null   float64
 9   Epoch Osculation             4687 non-null   float64
 10  Eccentricity                 4687 non-null   float64
 11  Semi Major Axis              4687 non-null   float64
 12  Inclination                  4687 non-null   float64
 13  Asc Node Longitude           4687 non-null   float64
 14  Orbital Period               4687 non-null   float64
 15  Perihelion Distance          4687 non-null   float64
 16  Perihelion Arg               4687 non-null   float64
 17  Aphelion Dist                4687 non-null   float64
 18  Perihelion Time              4687 non-null   float64
 19  Mean Anomaly                 4687 non-null   float64
 20  Mean Motion                  4687 non-null   float64
 21  Equinox                      4687 non-null   object
 22  Hazardous                    4687 non-null   int32
dtypes: float64(19), int32(1), int64(1), object(2)
memory usage: 824.0+ KB

#### Exploring the important features to work on :

We will start by exploring the correlation factors between the features within the dataset and the hazardness of the asteroids